//AUTHENTICATION (auth)
export const OPEN_AUTH_MODAL = 'OPEN_AUTH_MODAL'
export const CLOSE_AUTH_MODAL = 'CLOSE_AUTH_MODAL'
export const SIGN_IN_VALIDATION_SUCCESS = 'SIGN_IN_VALIDATION_SUCCESS'
export const SIGN_OUT = 'SIGN_OUT'

//DASHBOARD
export const TOGGLE_CARDS = 'TOGGLE_CARDS'
export const FETCH_STATUS_BUTTONS_SUCCESS = 'FETCH_STATUS_BUTTONS_SUCCESS'
export const FETCH_FAILED = 'FETCH_FAILED'
export const OPEN_DASH_DRAWER = 'OPEN_DASH_DRAWER'
export const OPEN_DASH_DRAWER_START = 'OPEN_DASH_DRAWER_START'
export const FETCH_DASH_DRAWER_SUCCESS = 'FETCH_DASH_DRAWER_SUCCESS'
export const CLOSE_DASH_DRAWER = 'CLOSE_DASH_DRAWER'
export const FETCH_STATUS_SUMMARY_SUCCESS = 'FETCH_STATUS_SUMMARY_SUCCESS'
