//GENERAL
export const FETCH_FAILED = 'FETCH_FAILED'

//AUTHENTICATION (auth)
export const OPEN_AUTH_MODAL = 'OPEN_AUTH_MODAL'
export const CLOSE_AUTH_MODAL = 'CLOSE_AUTH_MODAL'
export const SIGN_IN_START = 'SIGN_IN_START'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const SIGN_OUT = 'SIGN_OUT'

//DASHBOARD
export const TOGGLE_CARDS = 'TOGGLE_CARDS'
export const OPEN_DASH_DRAWER = 'OPEN_DASH_DRAWER'
export const OPEN_DASH_DRAWER_START = 'OPEN_DASH_DRAWER_START'
export const FETCH_DASH_DRAWER_SUCCESS = 'FETCH_DASH_DRAWER_SUCCESS'
export const CLOSE_DASH_DRAWER = 'CLOSE_DASH_DRAWER'
export const FETCH_STATUS_SUMMARY_SUCCESS = 'FETCH_STATUS_SUMMARY_SUCCESS'
export const FETCH_STATUS_TABLE_START = 'FETCH_STATUS_TABLE_START'
export const FETCH_STATUS_TABLE_SUCCESS = 'FETCH_STATUS_TABLE_SUCCESS'

//INSTRUMENTS
export const FETCH_INSTRUMENTS_TABLE_START = 'FETCH_INSTRUMENTS_TABLE_START'
export const FETCH_INSTRUMENTS_TABLE_SUCCESS = 'FETCH_INSTRUMENTS_TABLE_SUCCESS'
export const TOGGLE_AVAILABLE_SWITCH_START = 'TOGGLE_AVAILABLE_SWITCH_START'
export const TOGGLE_AVAILABLE_SWITCH_SUCCESS = 'TOGGLE_AVAILABLE_SWITCH_SUCCESS'
export const TOGGLE_INSTRUMENT_FORM = 'TOGGLE_INSTRUMENT_FORM'
